# ─────────────────────────────────────────────────────────────────────────────
# Eventa — ProGuard / R8 rules
# ─────────────────────────────────────────────────────────────────────────────

# Keep line numbers for crash reports
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# ── Kotlinx Serialization ───────────────────────────────────────────────────
# Keep the @Serializable annotation and the generated serializer companion
# objects so R8 doesn't strip them.
-keepattributes *Annotation*, InnerClasses
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep all @Serializable classes and their companion serializer() methods.
-keep,includedescriptorclasses class com.kosd.eventa.models.**$$serializer { *; }
-keepclassmembers class com.kosd.eventa.models.** {
    *** Companion;
}
-keepclasseswithmembers class com.kosd.eventa.models.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep @SerialName annotations
-keepattributes RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations

# ── Supabase Kotlin SDK ─────────────────────────────────────────────────────
-keep class io.github.jan.supabase.** { *; }
-keep class io.github.jan.supabase.**.* { *; }
# Keep RPC response wrapper classes (decoded via reflection)
-keepclassmembers class io.github.jan.supabase.postgrest.** {
    <init>(...);
}

# ── Ktor Client ─────────────────────────────────────────────────────────────
-keep class io.ktor.** { *; }
-keepclassmembers class io.ktor.** {
    <init>(...);
}
# Ktor uses reflection for plugin discovery
-keep class io.ktor.client.plugins.** { *; }
-keep class io.ktor.client.engine.android.** { *; }

# ── Kotlin Coroutines ───────────────────────────────────────────────────────
-keepclassmembers class kotlinx.coroutines.** {
    volatile <fields>;
}

# ── Compose ─────────────────────────────────────────────────────────────────
# Compose is generally safe with R8, but keep the runtime
-dontwarn androidx.compose.**

# ── AndroidX / DataStore ────────────────────────────────────────────────────
-keep class androidx.datastore.** { *; }
-keep class androidx.biometric.** { *; }

# ── ZXing (QR code generation) ──────────────────────────────────────────────
-keep class com.google.zxing.** { *; }
-keepclassmembers class com.google.zxing.** {
    <init>(...);
}

# ── OSMDroid ────────────────────────────────────────────────────────────────
-keep class org.osmdroid.** { *; }

# ── App models (reflection-safe) ────────────────────────────────────────────
# Keep all model data classes — they're decoded via kotlinx.serialization
-keep class com.kosd.eventa.models.** { *; }

# ── BuildConfig (contains Supabase URL/key) ─────────────────────────────────
-keep class com.kosd.eventa.BuildConfig { *; }

# ── Enums used in serialization ─────────────────────────────────────────────
-keepclassmembers enum com.kosd.eventa.models.** {
    **[] $VALUES;
    public *;
}

# ── Missing classes (auto-generated by R8) ──────────────────────────────────
# Ktor references these JMX classes for IDE debug detection — not available on Android.
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
